-- MySQL Script generated by MySQL Workbench
-- 04/15/15 01:14:03
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydbb_auditoria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tab_estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tab_estudiantes` (
  `idtab_estudiantes` INT NOT NULL,
  `cedula` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(10) NULL,
  PRIMARY KEY (`idtab_estudiantes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tab_materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tab_materias` (
  `idtab_materias` INT NOT NULL,
  `materia` VARCHAR(45) NULL,
  PRIMARY KEY (`idtab_materias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tab_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tab_notas` (
  `idtab_notas` INT NOT NULL,
  `nota` DECIMAL NULL,
  `tab_estudiantes_idtab_estudiantes` INT NOT NULL,
  `tab_materias_idtab_materias` INT NOT NULL,
  PRIMARY KEY (`idtab_notas`),
  INDEX `fk_tab_notas_tab_estudiantes_idx` (`tab_estudiantes_idtab_estudiantes` ASC),
  INDEX `fk_tab_notas_tab_materias1_idx` (`tab_materias_idtab_materias` ASC),
  CONSTRAINT `fk_tab_notas_tab_estudiantes`
    FOREIGN KEY (`tab_estudiantes_idtab_estudiantes`)
    REFERENCES `tab_estudiantes` (`idtab_estudiantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_notas_tab_materias1`
    FOREIGN KEY (`tab_materias_idtab_materias`)
    REFERENCES `tab_materias` (`idtab_materias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tab_auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tab_auditoria` (
  `idtab_auditoria` INT NOT NULL,
  `ip` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `trama` VARCHAR(45) NULL,
  `tiempo` TIME NULL,
  PRIMARY KEY (`idtab_auditoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tab_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tab_usuarios` (
  `idtab_usuarios` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `tipo_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idtab_usuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
